### PR TITLE
Add Reek config files support

### PR DESCRIPTION
**Pull request by smileart**
Hi! I've added Reek's config files support and its own settings parameter. By default, it's trying to find `config.reek` in the project's first folder. If there is no one it works as usual - with defaults. If you change setting to let's say `test.reek` it looks for this new file and if it was found `-c` option would be used. Looking forward to seeing it in the release, cause I think it's really useful feature. Thanks! 🤓

### CODE REVIEW

**Comment by ahmadseleem** [comment]
Thanks for contributing, and sorry for late response, Hopefully, I should look onto that in a few days and at first glance, it looks fine!
Thanks again!

**Comment by smileart** [comment]
@ahmadseleem Thank you for useful plugin ;) Hope to see these and other changes in production soon. Cheers! 😉

**Comment by ahmadseleem** [comment]
Thanks, again, I'm sorry, Frankly, I'm recovering from some health issues and so. Thanks for your patient :)

**Comment by smileart** [comment]
@ahmadseleem NP, man! I understand. We are all people here. Get well soon 👌

**Pull request merged**
